project_id = "sfddyljruhtqfwexyrra"

[functions.melhorenvio-authorize]
verify_jwt = false

[functions.melhorenvio-callback]
verify_jwt = false

[functions.melhorenvio-ping]
verify_jwt = false

[functions.melhorenvio-quote]
verify_jwt = false

[functions.melhorenvio-cart]
verify_jwt = false

[functions.melhorenvio-checkout]
verify_jwt = false

[functions.melhorenvio-label]
verify_jwt = false

[functions.melhorenvio-set-token]
verify_jwt = false

[functions.melhorenvio-get-token-status]
verify_jwt = false

[functions.order-create]
verify_jwt = false

[functions.paypal-create-order]
verify_jwt = false

[functions.paypal-capture-order]
verify_jwt = false

[functions.paypal-webhook]
verify_jwt = false

[functions.generate-label]
verify_jwt = false

[functions.asaas-create-pix]
verify_jwt = false

[functions.asaas-pay-credit-card]
verify_jwt = false

[functions.asaas-webhook]
verify_jwt = false

[functions.asaas-setup-webhook]
verify_jwt = false

[functions.asaas-stats]
verify_jwt = false

[functions.public-order-status]
verify_jwt = false


[functions.admin-provision]
verify_jwt = false
